# Generated by Django 5.0.1 on 2024-01-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='wish_list_a_last_na_ea050b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PresentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list_app.presentuser')),
            ],
            options={
                'ordering': ['list_name'],
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('offer_url', models.URLField()),
                ('image_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reserved', models.BooleanField(default=False)),
                ('present_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list_app.presentlist')),
                ('reserved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wish_list_app.presentuser')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='presentlist',
            index=models.Index(fields=['list_user'], name='wish_list_a_list_us_8bf2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='present',
            index=models.Index(fields=['created'], name='wish_list_a_created_694ea5_idx'),
        ),
    ]
