# Generated by Django 5.0.1 on 2024-01-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentlist',
            name='list_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_lists', to='wish_list_app.presentuser'),
        ),
    ]
